insert into restaurante_entity (codigo, nombre, nombreCiudad) values (1, 'Zoozzy', 'Néa Palátia');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (2, 'Leexo', 'Amizmiz');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (3, 'Browseblab', 'Tongguan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (4, 'Divavu', 'Maddela');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (5, 'Twitternation', 'Mākū');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (6, 'Oozz', 'Zuénoula');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (7, 'Livetube', 'New Plymouth');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (8, 'Quatz', 'Dingqiao');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (9, 'Voonix', 'Río Grande');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (10, 'Feedmix', 'Montego Bay');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (11, 'Thoughtstorm', 'Tonghae');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (12, 'Kazio', 'Verkhniye Osel’ki');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (13, 'Camimbo', 'Thompson');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (14, 'Quatz', 'Wola Rębkowska');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (15, 'Pixonyx', 'San Jerónimo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (16, 'Kwimbee', 'Coutances');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (17, 'Jabbersphere', 'Wunat');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (18, 'Yakitri', 'Balgarevo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (19, 'Skalith', 'Polo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (20, 'Kaymbo', 'Mondragon');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (21, 'Quinu', 'Jagistay');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (22, 'Quatz', 'Umeå');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (23, 'Buzzbean', 'Shuyuan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (24, 'Camimbo', 'Bulnes');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (25, 'Twimm', 'Stavyshche');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (26, 'Gabspot', 'Chachagüí');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (27, 'Voolith', 'Itapemirim');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (28, 'Agimba', 'Barotac Nuevo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (29, 'Linklinks', 'Dschang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (30, 'Skimia', 'Mira');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (31, 'Thoughtmix', 'Vievis');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (32, 'Linkbuzz', 'São Gotardo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (33, 'Tagtune', 'Niopanda');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (34, 'Plambee', 'Augusta');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (35, 'Zoovu', 'Covão');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (36, 'Eare', 'Sang-e Māshah');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (37, 'Buzzdog', 'Kaltan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (38, 'Trudeo', 'Mercaderes');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (39, 'Flipbug', 'Tolomango');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (40, 'Eamia', 'Cañete');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (41, 'Feedfish', 'Nanga Eboko');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (42, 'Rhynoodle', 'Kuala Terengganu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (43, 'Demizz', 'Ban Lam Luk Ka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (44, 'Bubblebox', 'Plewiska');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (45, 'Livefish', 'Brades');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (46, 'Skalith', 'Kitapak');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (47, 'Kwinu', 'Saumur');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (48, 'Gigashots', 'Singabarong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (49, 'Devpulse', 'Cengang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (50, 'Trudeo', 'Maoping');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (51, 'Yakitri', 'Aeteke');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (52, 'Leenti', 'Mansilingan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (53, 'Chatterpoint', 'Solna');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (54, 'Lajo', 'Sanshan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (55, 'Layo', 'Talata Mafara');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (56, 'Bubblemix', 'Kamen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (57, 'Divanoodle', 'Waalwijk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (58, 'Livetube', 'Sölvesborg');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (59, 'Vimbo', 'Tulyushka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (60, 'Yodoo', 'Lamarosa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (61, 'Roodel', 'Palampal');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (62, 'Gabspot', 'Bao’an');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (63, 'Rhynyx', 'Esik');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (64, 'Npath', 'Kuroishi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (65, 'Yoveo', 'Demerval Lobão');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (66, 'Lajo', 'Dachong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (67, 'Livepath', 'Głogów Małopolski');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (68, 'Wikido', 'Mrozy');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (69, 'Gabtype', 'Cikeper');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (70, 'Wikizz', 'Gatbo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (71, 'Skyndu', 'Jingdang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (72, 'Ntags', 'Cairani');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (73, 'Voomm', 'Kasoa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (74, 'Eire', 'Neochóri');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (75, 'Camimbo', 'Amarillo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (76, 'Voonte', 'Sundbyberg');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (77, 'Snaptags', 'New Haven');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (78, 'Quinu', 'Gangbian');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (79, 'Devshare', 'Despotovac');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (80, 'Centizu', 'Datartua');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (81, 'Katz', 'Iradan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (82, 'Aibox', 'Fengtai Chengguanzhen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (83, 'Twitternation', 'Victoria');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (84, 'Pixonyx', 'Jalālābād');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (85, 'DabZ', 'Kurortnyy');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (86, 'Bubblebox', 'Huacheng');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (87, 'Babbleset', 'Isla Pucú');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (88, 'Yozio', 'Fifi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (89, 'Devify', 'Shangkuli');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (90, 'Eidel', 'Pahonjean');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (91, 'Demizz', 'Arteche');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (92, 'Fivebridge', 'Chai Badan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (93, 'Youopia', 'Maoping');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (94, 'Flipstorm', 'Vännäs');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (95, 'Skyndu', 'Mukayrās');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (96, 'Edgeblab', 'Fangcun');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (97, 'Jaxworks', 'Khafizan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (98, 'Youbridge', 'Lac La Biche');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (99, 'Browsetype', 'Khŭjand');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (100, 'Jaxworks', 'Sukth');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (101, 'Katz', 'Gò Dầu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (102, 'Eayo', 'Sandvika');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (103, 'Yodel', 'Nishio');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (104, 'Plajo', 'Shangzhuang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (105, 'Yambee', 'Chugur');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (106, 'Leexo', 'Asyūţ');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (107, 'Rhycero', 'Armação de Búzios');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (108, 'Wordpedia', 'Brněnec');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (109, 'Rooxo', 'Sebewe');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (110, 'Flashpoint', 'Loay');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (111, 'Jetwire', 'Biasong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (112, 'Centidel', 'Debre Mark’os');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (113, 'Yodo', 'Slobodskoy');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (114, 'Npath', 'Masape');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (115, 'Realbridge', 'Lyon');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (116, 'Jabberstorm', 'Dete');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (117, 'Jaxspan', 'Nagbacalan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (118, 'Twitterwire', 'Gutang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (119, 'Kwinu', 'Rakičan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (120, 'Trilith', 'Jardín');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (121, 'Aimbu', 'Matinao');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (122, 'Buzzdog', 'Pisarzowice');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (123, 'Meevee', 'Mariestad');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (124, 'Browsezoom', 'Pagedangan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (125, 'Riffpath', 'Prachamtakham');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (126, 'Blogtags', 'Santa Cruz');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (127, 'Meevee', 'Australia Square');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (128, 'Mydeo', 'Hitura');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (129, 'Ailane', 'Xindeng');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (130, 'Zoonder', 'Casal das Figueiras');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (131, 'Zooveo', 'Cigaras');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (132, 'Jayo', 'Masaraway');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (133, 'Dynazzy', 'Tokmok');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (134, 'Dynabox', 'Lao Suea Kok');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (135, 'Babbleblab', 'Tiaodeng');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (136, 'Fivebridge', 'Bochum');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (137, 'Latz', 'Boniewo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (138, 'Flashpoint', 'Lobão');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (139, 'Feednation', 'Luntai');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (140, 'Eamia', 'Muranovo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (141, 'Demivee', 'Liwonde');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (142, 'Tagchat', 'Zalaegerszeg');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (143, 'Brightbean', 'Tiguion');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (144, 'Rhycero', 'Longbei');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (145, 'Babbleblab', 'Toukh');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (146, 'Dabvine', 'Verkhnyachka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (147, 'Flipopia', 'Hønefoss');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (148, 'Blogtags', 'Wanghu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (149, 'Trupe', 'Kamiennik');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (150, 'Eazzy', 'El Doncello');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (151, 'Brightdog', 'Wenshui');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (152, 'Thoughtsphere', 'Simão Dias');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (153, 'Yambee', 'Pyrzyce');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (154, 'Oyoba', 'Maguan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (155, 'Ozu', 'Magnitogorsk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (156, 'Topiclounge', 'Fushan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (157, 'Avaveo', 'Jaworzynka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (158, 'Meevee', 'Kopang Satu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (159, 'Yakijo', 'Wunat');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (160, 'Oodoo', 'Yuanba');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (161, 'Tambee', 'Myślenice');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (162, 'Demimbu', 'Yangcun');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (163, 'Rhynyx', 'Nancy');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (164, 'Oyonder', 'Cachoeirinha');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (165, 'Devshare', 'Baucau');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (166, 'Photobug', 'Austin');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (167, 'Topdrive', 'Évry');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (168, 'Skipstorm', 'Gazanjyk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (169, 'Wikizz', 'Pajung');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (170, 'Bluejam', 'Bieniewice');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (171, 'Jabbersphere', 'Isdalstø');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (172, 'Wordtune', 'Marcabamba');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (173, 'Edgewire', 'Garisul');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (174, 'Realpoint', 'Mandor');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (175, 'Jaloo', 'New Orleans');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (176, 'Edgeify', 'Qiaotou');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (177, 'Ntag', 'Librazhd-Qendër');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (178, 'Meedoo', 'Umeå');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (179, 'Buzzbean', 'Candelaria');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (180, 'Rhycero', 'Kłoczew');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (181, 'Gigabox', 'Lücheng');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (182, 'Photobean', 'Bremen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (183, 'Roomm', 'Cheremnoye');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (184, 'Skippad', 'Lamas');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (185, 'Youspan', 'Taveiro');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (186, 'Oodoo', 'Erechim');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (187, 'Demimbu', 'Svitlovods’k');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (188, 'Realcube', 'Privolzhsk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (189, 'Dabtype', 'Birsa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (190, 'Wordpedia', 'Lusk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (191, 'Realblab', 'Ageoshimo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (192, 'Skippad', 'Esperantina');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (193, 'Mynte', 'Gomunice');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (194, 'Twinte', 'Tanumshede');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (195, 'Agivu', 'Maardu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (196, 'Digitube', 'Hepingjie');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (197, 'Tagopia', 'Hŭngju-dong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (198, 'Buzzster', 'Veldhoven');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (199, 'Yakijo', 'Zaprudnya');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (200, 'Realcube', 'Baltiysk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (201, 'Tekfly', 'Lechinkay');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (202, 'Photojam', 'Longtou');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (203, 'Rooxo', 'Banjar Brahmanabukit');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (204, 'Blogtag', 'Могила');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (205, 'Divape', 'Chegdomyn');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (206, 'Avavee', 'Słotowa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (207, 'Flipbug', 'Denver');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (208, 'Divanoodle', 'Bom Jesus do Itabapoana');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (209, 'Skaboo', 'Pital');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (210, 'Dynabox', 'Xiaohebian');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (211, 'Brainsphere', 'Orange');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (212, 'Photojam', 'Calabugao');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (213, 'Voonte', 'Achadinha');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (214, 'LiveZ', 'Sete Cidades');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (215, 'Buzzbean', 'Yushan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (216, 'Quinu', 'Al Misrākh');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (217, 'Aimbu', 'Boujniba');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (218, 'Shuffledrive', 'Yelyzavethradka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (219, 'Trudoo', 'Sundsvall');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (220, 'Flashpoint', 'Phanom Phrai');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (221, 'Fivespan', 'Kamba');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (222, 'Kanoodle', 'Žabljak');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (223, 'Kwimbee', 'Baiima');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (224, 'Zooveo', 'Jingyu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (225, 'Zoomcast', 'Neni');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (226, 'Podcat', 'Darkovice');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (227, 'Trunyx', 'Sundsvall');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (228, 'Brainsphere', 'Gorna Oryakhovitsa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (229, 'Meevee', 'Torre de Moncorvo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (230, 'Gabtype', 'Miastków Kościelny');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (231, 'Livetube', 'Rudka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (232, 'Avamba', 'Cabeças Verdes');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (233, 'Fivechat', 'Ganhe');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (234, 'Oyonder', 'Khamis Mushait');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (235, 'Feedspan', 'Yoichi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (236, 'Realfire', 'Illela');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (237, 'Zooveo', 'Feira de Santana');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (238, 'Shufflebeat', 'Qırmızı Samux');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (239, 'Shufflester', 'Jingxiyuan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (240, 'Reallinks', 'Alderetes');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (241, 'Mycat', 'Paris 10');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (242, 'Lazz', 'Kembangarum');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (243, 'Trupe', 'Cabaiguán');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (244, 'Skyba', 'Bánica');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (245, 'Photobug', 'Puerres');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (246, 'Edgeclub', 'Banjar Kertasari');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (247, 'Thoughtblab', 'Pimbalayan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (248, 'Skynoodle', 'Zaolin');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (249, 'Twinder', 'Tríkala');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (250, 'Voonyx', 'Baoshan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (251, 'Plajo', 'Lívingston');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (252, 'Youspan', 'Xinkaikou');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (253, 'Cogilith', 'Freetown');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (254, 'Fliptune', 'Arlington');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (255, 'Kwimbee', 'Shakhun’ya');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (256, 'Riffwire', 'Lampitak');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (257, 'Skyble', 'Xilópolis');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (258, 'Mydeo', 'Matayumtayum');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (259, 'Skyndu', 'Al Muwayh');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (260, 'Devify', 'Looc');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (261, 'Eidel', 'Kamárai');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (262, 'Dabtype', 'Jiḩānah');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (263, 'Zoonder', 'Mayong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (264, 'Centizu', 'Xunjian');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (265, 'Meejo', 'Karabash');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (266, 'Zazio', 'Tsukumiura');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (267, 'Realcube', 'Zhongxin');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (268, 'Ainyx', 'Datangzhuang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (269, 'Edgeclub', 'Tetovo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (270, 'Oyonder', 'Muarasiau');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (271, 'Feedfire', 'Sidomulyo Kulon');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (272, 'Rhynoodle', 'Stockholm');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (273, 'Blogtag', 'Labansari');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (274, 'Trudoo', 'Gilowice');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (275, 'Thoughtblab', 'Binzhou');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (276, 'Riffpedia', 'Majdal Banī Fāḑil');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (277, 'Zazio', 'Cilegong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (278, 'Skivee', 'Arrap’i');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (279, 'Skinix', 'Hisya');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (280, 'Twitterworks', 'Saint-Chamond');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (281, 'Kanoodle', 'Shinjō');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (282, 'Ntag', 'Khao Yoi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (283, 'Feednation', 'Wuli');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (284, 'Meevee', 'Zoumaling');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (285, 'Leexo', 'Miguel Pereira');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (286, 'Voomm', 'San Andres');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (287, 'Skyble', 'Eybens');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (288, 'BlogXS', 'Manaquiri');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (289, 'Bluezoom', 'Gorna Oryakhovitsa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (290, 'Digitube', 'Sarvaš');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (291, 'Agivu', 'Itapema');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (292, 'Jabbersphere', 'Pancheng');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (293, 'Zooxo', 'Ipatinga');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (294, 'Cogilith', 'Shahrīār');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (295, 'Dabjam', 'Grugul');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (296, 'Katz', 'Kukichūō');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (297, 'Buzzbean', 'Pointe-à-Pitre');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (298, 'Jaxworks', 'Gonghe');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (299, 'Voolith', 'Tanshi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (300, 'Trudoo', 'Anhai');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (301, 'Wikivu', 'Vista Hermosa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (302, 'Geba', 'Huitán');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (303, 'Zoonder', 'Oekuu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (304, 'Twitterlist', 'Tandil');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (305, 'Dynabox', 'Puračić');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (306, 'Trilia', 'Al Jumaylīyah');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (307, 'Jazzy', 'Chelbasskaya');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (308, 'Geba', 'Puutuga');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (309, 'Trilia', 'Kwaluseni');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (310, 'Nlounge', 'Ladoang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (311, 'Eazzy', 'Maple Ridge');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (312, 'Rhynoodle', 'Furong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (313, 'Bubbletube', 'Nueva Cajamarca');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (314, 'Skipstorm', 'Longchiqiao');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (315, 'Meeveo', 'Tonghu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (316, 'Jayo', 'Akaki');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (317, 'Brightbean', 'les Escaldes');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (318, 'Demivee', 'Jinping');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (319, 'Realcube', 'San Rafael');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (320, 'Quimm', 'Perštejn');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (321, 'Skinder', 'Rosmaninhal');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (322, 'Kazio', 'Grand Junction');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (323, 'Reallinks', 'Al Jīb');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (324, 'Gabtype', 'São Sebastião');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (325, 'Eadel', 'Peruc');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (326, 'Mita', 'Volokolamsk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (327, 'Cogilith', 'Rondonópolis');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (328, 'Babbleset', 'Hejiadong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (329, 'Twitterbridge', 'Vailoa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (330, 'Voolith', 'Anningqu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (331, 'Janyx', 'Sampaloc');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (332, 'Jabberstorm', 'Schieren');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (333, 'Thoughtbridge', 'Strážná');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (334, 'Topdrive', 'Sumberkertokrajan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (335, 'Riffpedia', 'Beixinjie');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (336, 'InnoZ', 'Balagon');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (337, 'Skivee', 'Stende');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (338, 'Npath', 'Mahe');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (339, 'Avamm', 'Kamo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (340, 'Oozz', 'Motomiya');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (341, 'Skyble', 'Ribnica na Pohorju');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (342, 'Yodo', 'Piracaia');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (343, 'Miboo', 'Vila Flor');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (344, 'Vinte', 'Paraíso');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (345, 'Wordtune', 'Puerto Rico');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (346, 'Roombo', 'Toride');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (347, 'Fivechat', 'Dubrovka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (348, 'Jaloo', 'Corumbá');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (349, 'JumpXS', 'Wāling');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (350, 'Twimm', 'Bang Khon Thi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (351, 'Browsedrive', 'Hashaat');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (352, 'Shuffletag', 'Corgo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (353, 'Meejo', 'Lughaye');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (354, 'Wordware', 'Potongan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (355, 'Yakijo', 'Storuman');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (356, 'Izio', 'Itami');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (357, 'Photojam', 'Słupno');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (358, 'Quinu', 'Sukaharja');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (359, 'Midel', 'Lushuihe');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (360, 'Babblestorm', 'Santa Cecilia');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (361, 'Katz', 'Ordino');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (362, 'Tambee', 'Galapa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (363, 'Zoomdog', 'Fílla');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (364, 'Realbridge', 'Nangkapayung');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (365, 'Topicshots', 'Yunxi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (366, 'Skynoodle', 'Tororo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (367, 'Ainyx', 'Guicheng');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (368, 'Voolith', 'Malonty');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (369, 'Topicblab', 'Solec Nad Wisłą');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (370, 'Gigazoom', 'Litein');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (371, 'Youspan', 'Bandhagen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (372, 'Quaxo', 'Llorente');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (373, 'Kamba', 'Maizuru');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (374, 'Meevee', 'Prachin Buri');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (375, 'Skyndu', 'Gambarjati');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (376, 'Dabtype', 'Kiambu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (377, 'Twitternation', 'Guofu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (378, 'Edgeify', 'Bethanie');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (379, 'Livetube', 'Doibang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (380, 'Vinte', 'Capalayan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (381, 'Youspan', 'Zabaykal’sk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (382, 'Riffpedia', 'Boncong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (383, 'Chatterpoint', 'Nanortalik');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (384, 'Aimbu', 'Sundsvall');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (385, 'Jabbersphere', 'Vilar do Pinheiro');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (386, 'Skyble', 'Dragomer');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (387, 'Skajo', 'Santol');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (388, 'Aivee', 'Rancho Nuevo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (389, 'Ntags', 'Hexi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (390, 'Aimbu', 'Ikoma');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (391, 'Jatri', 'Mafra');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (392, 'Lazzy', 'Barengkok');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (393, 'Innotype', 'Alannay');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (394, 'Oyoloo', 'Yamango');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (395, 'Wikivu', 'Ostrów Mazowiecka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (396, 'Realbuzz', 'Honglong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (397, 'Eadel', 'Riihimäki');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (398, 'Meembee', 'El Carmen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (399, 'Dynazzy', 'Sorongan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (400, 'Skinte', 'Ciburial');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (401, 'Twitterbridge', 'Sidoaji');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (402, 'Realbridge', 'Chimtāl');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (403, 'Brainverse', 'Cáchira');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (404, 'Zoomcast', 'Porirua');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (405, 'Lajo', 'Porsgrunn');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (406, 'Thoughtblab', 'Soba');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (407, 'Agivu', 'Dengteke');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (408, 'Browsedrive', 'Inkerman');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (409, 'Yambee', 'Rivas');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (410, 'Quimm', 'Jindayris');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (411, 'Jetpulse', 'Cipari');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (412, 'LiveZ', 'Tovačov');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (413, 'Topicblab', 'Wenquan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (414, 'Eimbee', 'Jām Sāhib');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (415, 'Youspan', 'Huangjin');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (416, 'Jaxworks', 'Villiers');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (417, 'Topicware', 'Cherryville');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (418, 'Plambee', 'Buturlinovka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (419, 'Bubblebox', 'Ivanivka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (420, 'Youbridge', 'Xiangcunxiang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (421, 'Bluejam', 'Ciburial');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (422, 'Pixope', 'Qufu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (423, 'Katz', 'Jinquan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (424, 'Kazu', 'Yuecheng');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (425, 'Skivee', 'Yuzhai');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (426, 'Wordtune', 'Yangxiang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (427, 'Dabfeed', 'Alvesta');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (428, 'Meembee', 'That Phanom');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (429, 'Jayo', 'Malichang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (430, 'Realbridge', 'Lincuo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (431, 'Yabox', 'Příbor');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (432, 'Feedbug', 'Tandel');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (433, 'Photojam', 'Beima');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (434, 'Linklinks', 'Nonohonis');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (435, 'Fiveclub', 'Ginebra');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (436, 'Linktype', 'Xambabazar');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (437, 'Yabox', 'Panganiban');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (438, 'Skajo', 'Cotabato');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (439, 'Browsecat', 'Simeykyne');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (440, 'Youbridge', 'Batas Barat');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (441, 'Divanoodle', 'Huatan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (442, 'Bubblebox', 'Lagoa Seca');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (443, 'Bubbletube', 'Ḩawsh ‘Īsá');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (444, 'Layo', 'Al Jaghbūb');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (445, 'Kaymbo', 'Schiedam postbusnummers');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (446, 'Fadeo', 'Arraial do Cabo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (447, 'Muxo', 'Yongfeng');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (448, 'Realpoint', 'Dungang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (449, 'Skidoo', 'Stockholm');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (450, 'Tazzy', 'Strunino');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (451, 'Buzzbean', 'Saga');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (452, 'Yadel', 'Vodňany');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (453, 'Feedbug', 'Cete');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (454, 'Livepath', 'Mengdadazhuang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (455, 'Browsezoom', 'Xiasi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (456, 'Voomm', 'Teno');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (457, 'Brainverse', 'Nichinan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (458, 'Linklinks', 'Shitouhe');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (459, 'Ainyx', 'Frederico Westphalen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (460, 'Riffpedia', 'Kowary');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (461, 'Eare', 'Baabda');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (462, 'Twitternation', 'San Jose');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (463, 'Wordtune', 'Gijon');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (464, 'Youfeed', 'Mbanga');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (465, 'Zava', 'Masoli');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (466, 'Dynava', 'Ōmachi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (467, 'Vitz', 'Fenais da Ajuda');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (468, 'Yakidoo', 'Nanyo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (469, 'Tagtune', 'Barentu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (470, 'Livetube', 'Vinica');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (471, 'Zoomdog', 'Sergiyev Posad');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (472, 'Topicstorm', 'Marapat');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (473, 'Abatz', 'Yambol');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (474, 'Roomm', 'San Benito');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (475, 'Fivespan', 'Tungol');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (476, 'Youfeed', 'Sukabumi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (477, 'Camimbo', 'Douz');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (478, 'Feedmix', 'Barţa‘ah ash Sharqīyah');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (479, 'Eazzy', 'Chenji');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (480, 'Buzzshare', 'Enriquillo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (481, 'Roomm', 'San Miguel');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (482, 'Browsebug', 'Malawa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (483, 'Jayo', 'Hudong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (484, 'Plajo', 'Lyamino');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (485, 'Wordware', 'Kerep Wetan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (486, 'Oyope', 'Castro');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (487, 'Yozio', 'Fengchuan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (488, 'Jamia', 'Ciudad Bolívar');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (489, 'Yoveo', 'Ponte Nova');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (490, 'Twimm', 'Gengzhuang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (491, 'Riffpath', 'Rasūlnagar');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (492, 'Muxo', 'Liyang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (493, 'Voonder', 'Carvalhal da Aroeira');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (494, 'Zava', 'Cosquín');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (495, 'Jabbersphere', 'Tulsa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (496, 'Lazz', 'Lokolande');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (497, 'Avavee', 'Houping');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (498, 'Midel', 'Bajo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (499, 'Dabfeed', 'Lailunggi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (500, 'Brainlounge', 'Mapalad');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (501, 'Oyope', 'Jiangwakou');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (502, 'Wordpedia', 'Marull');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (503, 'Trilith', 'Orurillo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (504, 'Roomm', 'Poroshkovo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (505, 'Centidel', 'San Gabriel');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (506, 'Ooba', 'København');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (507, 'Wikibox', 'Dankalwa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (508, 'Bluezoom', 'Drajak');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (509, 'Tazz', 'Tame');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (510, 'Linkbuzz', 'Galitsy');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (511, 'Shuffletag', 'San Antonio');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (512, 'Voomm', 'Zhongzuiling');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (513, 'Layo', 'Rantau');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (514, 'Bubblebox', 'Santa Cruz');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (515, 'Omba', 'Eadestown');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (516, 'Mynte', 'Logan Lake');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (517, 'Rhyzio', 'Qiaojia');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (518, 'Wikivu', 'Nyrob');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (519, 'Zoomcast', 'Ljukovo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (520, 'Cogibox', 'Bekwai');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (521, 'Topiclounge', 'Ampera');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (522, 'Rhyloo', 'Kalashnikovo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (523, 'Nlounge', 'Sorodot');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (524, 'Browsezoom', 'Antwerpen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (525, 'Ntags', 'Taiyu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (526, 'Yamia', 'Tongyang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (527, 'Browsetype', 'Lemery');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (528, 'Divape', 'Besuki');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (529, 'Edgewire', 'Primorskiy');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (530, 'Youspan', 'Chinú');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (531, 'Bubblemix', 'Jasień');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (532, 'Plambee', 'Orleans');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (533, 'Rhyzio', 'Gritsovskiy');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (534, 'Eamia', 'Askaniya Nova');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (535, 'Skilith', 'Hrazdan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (536, 'Jaxnation', 'Kousséri');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (537, 'Thoughtbeat', 'Armentières');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (538, 'Izio', 'Galveias');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (539, 'Avamba', 'Ołpiny');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (540, 'Browsedrive', 'Cheping');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (541, 'Shuffledrive', 'Carcassonne');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (542, 'Quimm', 'Tangxing');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (543, 'Kwideo', 'Yongqin');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (544, 'Yabox', 'Kruševac');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (545, 'Topicblab', 'Vale Maceiras');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (546, 'Roombo', 'Kukulu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (547, 'Gigabox', 'Dalazi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (548, 'Twitterworks', 'Qingshanhu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (549, 'Zooveo', 'Qiqing');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (550, 'Flipopia', 'Thawi Watthana');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (551, 'Skyba', 'Yangjiaqiao');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (552, 'Skyble', 'Labin');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (553, 'Dynazzy', 'Río Grande');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (554, 'Izio', 'Santai');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (555, 'Buzzdog', 'Krajanpagowan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (556, 'Gevee', 'Geshan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (557, 'Linktype', 'Sishan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (558, 'Quinu', 'Cabimas');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (559, 'Yotz', 'Saint-Louis');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (560, 'Avamm', 'Two Hills');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (561, 'Devpulse', 'Słupsk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (562, 'Skiptube', 'Hobart');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (563, 'Centizu', 'Huaidao');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (564, 'Twimbo', 'Kut Chum');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (565, 'Zoombeat', 'Doom');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (566, 'Yodoo', 'Soasio');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (567, 'Gevee', 'Boracéia');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (568, 'Quatz', 'Banjar Dukuh');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (569, 'Voolith', 'Zengguang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (570, 'Gigabox', 'Montenegro');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (571, 'Devpulse', 'Balong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (572, 'Mudo', 'Tiehe');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (573, 'Edgeify', 'Aygepat');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (574, 'Meedoo', 'Taphan Hin');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (575, 'Jaxnation', 'Bolszewo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (576, 'Linktype', 'Đắk Song');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (577, 'Edgeify', 'Kebonagung');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (578, 'Feedfire', 'Álftanes');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (579, 'Vinte', 'Núi Sập');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (580, 'Thoughtbeat', 'Gorodishche');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (581, 'Camido', 'San Rafael');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (582, 'Skinte', 'Kuala Lumpur');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (583, 'Quire', 'Doksy');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (584, 'Oyondu', 'Diepsloot');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (585, 'Tekfly', 'Budenovetc');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (586, 'Skimia', 'Kabukarudi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (587, 'Jabbersphere', 'Jinzipai');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (588, 'Shuffledrive', 'Ibung');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (589, 'Oozz', 'Flying Fish Cove');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (590, 'Eimbee', 'Maofan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (591, 'Jayo', 'Basoko');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (592, 'Npath', 'Fteliá');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (593, 'Buzzshare', 'Dasiping');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (594, 'Livetube', 'Yasothon');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (595, 'Camido', 'Kyosai');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (596, 'Meezzy', 'Kālīganj');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (597, 'Kwilith', 'San Lorenzo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (598, 'Omba', 'Karang Tengah');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (599, 'Blogspan', 'Nong Bun Nak');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (600, 'Wikizz', 'Sofádes');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (601, 'Photojam', 'Kangani');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (602, 'Eare', 'Monteros');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (603, 'Topiclounge', 'Ptení');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (604, 'Abata', 'Nagorsk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (605, 'Realbridge', 'Mbuji-Mayi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (606, 'Wordtune', 'Puerres');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (607, 'Mudo', 'Killumney');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (608, 'Eamia', 'Vejprnice');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (609, 'Tagpad', 'Nunbaundelha');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (610, 'Blogspan', 'Puger');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (611, 'Twitterbeat', 'Marathon');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (612, 'Zoomcast', 'Zagnitkiv');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (613, 'Ooba', 'Banī Suhaylā');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (614, 'Blogtag', 'São Paio de Gramaços');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (615, 'Meetz', 'Enschede');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (616, 'Jabbertype', 'Monte Francisco');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (617, 'Yabox', 'Umanggudang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (618, 'DabZ', 'Taraban Timur');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (619, 'Devpoint', 'Fagersta');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (620, 'Yacero', 'Olympia');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (621, 'Fadeo', 'Novi Slankamen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (622, 'Yombu', 'Mapinrea');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (623, 'Agimba', 'Cookshire-Eaton');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (624, 'Realmix', 'Faisalābād');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (625, 'Tambee', 'Šentvid pri Stični');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (626, 'Fanoodle', 'Prior Velho');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (627, 'InnoZ', 'Santander');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (628, 'Wikizz', 'Daxing');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (629, 'Jabbersphere', 'Hövsan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (630, 'Brainsphere', 'Longquan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (631, 'Thoughtworks', 'Tongyangdao');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (632, 'Skipfire', 'Bojonegoro');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (633, 'Jatri', 'Donggou');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (634, 'Ntags', 'Ocote Paulino');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (635, 'Cogibox', 'Castle Bruce');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (636, 'Dabshots', 'Bagrāmī');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (637, 'Kwilith', 'Batawa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (638, 'Youtags', 'Lianokládhion');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (639, 'Thoughtsphere', 'Höfn');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (640, 'Centimia', 'Belfast');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (641, 'Thoughtstorm', 'Carlos Tejedor');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (642, 'Shufflester', 'Sanguinheira');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (643, 'Minyx', 'Asbestos');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (644, 'Demimbu', 'Liubo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (645, 'Jayo', 'Volodarsk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (646, 'Jabberbean', 'Shāhdādkot');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (647, 'Skinix', 'Lokossa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (648, 'Quire', 'General Pinedo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (649, 'Tagopia', 'Ajaccio');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (650, 'Voomm', 'Ibirataia');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (651, 'Quire', 'Kindersley');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (652, 'Realblab', 'Hongguang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (653, 'Pixope', 'Şuraabad');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (654, 'Yadel', 'Tieshan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (655, 'Demivee', 'Riga');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (656, 'Trupe', 'Kaavi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (657, 'Meedoo', 'Eg');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (658, 'Eidel', 'Duwayr Raslān');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (659, 'Quinu', 'Rosso');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (660, 'Oyondu', 'Hegeng');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (661, 'Rooxo', 'Quiñota');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (662, 'InnoZ', 'Ząbkowice Śląskie');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (663, 'Geba', 'Cañasgordas');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (664, 'Pixonyx', 'Pancol');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (665, 'Bluezoom', 'Kuala Baru');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (666, 'Oodoo', 'Petrozavodsk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (667, 'Thoughtstorm', 'Agriá');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (668, 'Wikido', 'Mugango');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (669, 'Dabfeed', 'Hiratachō');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (670, 'Oyondu', 'Hepingjie');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (671, 'Jaxnation', 'Huifa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (672, 'Zoomcast', 'Yuanzhou');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (673, 'Dabtype', 'Pražmo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (674, 'Jatri', 'Djibo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (675, 'Photolist', 'Líně');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (676, 'Lajo', 'Barbacena');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (677, 'Thoughtstorm', 'Gaoqiu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (678, 'Voomm', 'Tahala');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (679, 'Skipstorm', 'Vale da Serra');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (680, 'Divape', 'Gununglajang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (681, 'Browsecat', 'Zerkten');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (682, 'Topiczoom', 'Nesovice');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (683, 'Eayo', 'Kegeyli Shahar');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (684, 'Yozio', 'Bhisho');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (685, 'Skibox', 'Calizo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (686, 'Zoombeat', 'Rerawere');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (687, 'Fivechat', 'Huarong Chengguanzhen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (688, 'Eayo', 'Tymbark');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (689, 'Brightdog', 'Södertälje');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (690, 'Lajo', 'Temanjang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (691, 'Jaloo', 'Kipen’');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (692, 'Jamia', 'Santa Clara');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (693, 'Flashpoint', 'Uzda');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (694, 'JumpXS', 'Baie-Comeau');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (695, 'Twiyo', 'Fratar');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (696, 'Babblestorm', 'Ngujung');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (697, 'Jabbersphere', 'Los Frentones');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (698, 'Mynte', 'Luhe');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (699, 'Jabberbean', 'Stronie');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (700, 'Mynte', 'Piritiba');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (701, 'Babbleset', 'Gongping');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (702, 'Trupe', 'Kamphaeng Phet');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (703, 'Topicware', 'Vila Ribeiro');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (704, 'Kare', 'Catabola');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (705, 'Brainlounge', 'Embajador Martini');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (706, 'Tazz', 'Kuznetsovs’k');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (707, 'Voomm', 'Putrajaya');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (708, 'Voonyx', 'Maukaro');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (709, 'Podcat', 'Masaran');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (710, 'Zava', 'Saratak');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (711, 'Flipbug', 'Quetigny');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (712, 'Flashpoint', 'Caihua');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (713, 'Gabspot', 'Kayakent');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (714, 'Flashspan', 'Duboka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (715, 'Jaxworks', 'La Virgen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (716, 'Muxo', 'Tembang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (717, 'Vipe', 'Tuzhai');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (718, 'Jabberbean', 'Dayangzhou');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (719, 'Blogtag', 'Debrecen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (720, 'Zoombox', 'Klole');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (721, 'Skynoodle', 'Yanagawamachi-saiwaichō');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (722, 'Eabox', 'Muhos');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (723, 'Kanoodle', 'Bayt Sīrā');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (724, 'Eare', 'Da’ao');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (725, 'Devpulse', 'Krajan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (726, 'Myworks', 'Lanot');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (727, 'Wordpedia', 'Semuda');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (728, 'Mita', 'Bethel Town');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (729, 'Oyondu', 'Begowāla');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (730, 'Jaxnation', 'Krzemieniewo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (731, 'Twitterwire', 'Xaçmaz');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (732, 'Camimbo', 'Vetlanda');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (733, 'Skalith', 'Urukh');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (734, 'Voonix', 'Liloan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (735, 'Minyx', 'Campanário');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (736, 'Eare', 'Weifang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (737, 'Zoomzone', 'Caçador');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (738, 'Fivebridge', 'Bardīyah');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (739, 'Dabfeed', 'Kant');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (740, 'Meetz', 'Kagoshima-shi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (741, 'Camido', 'Bailianhe');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (742, 'Bubblebox', 'Zapatero');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (743, 'Yacero', 'Kahnūj');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (744, 'Eadel', 'Sumber');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (745, 'Zoovu', 'Leworook');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (746, 'Jazzy', 'Pingshi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (747, 'Tanoodle', 'Daeosin Satu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (748, 'Quimm', 'Trondheim');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (749, 'Divavu', 'Évreux');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (750, 'Youspan', 'Kaliasin');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (751, 'Twimm', 'Ramadi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (752, 'Wordware', 'Río Grande');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (753, 'Twitterworks', 'Lennec');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (754, 'Leenti', 'San Andres');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (755, 'Jabbersphere', 'West End');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (756, 'Yakitri', 'Niitsu-honchō');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (757, 'Npath', 'El’brus');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (758, 'Browsezoom', 'Estrada');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (759, 'Jetwire', 'Huyuan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (760, 'Photospace', 'Marmande');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (761, 'Aimbu', 'Vidzy');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (762, 'Voolith', 'Pasto');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (763, 'Jazzy', 'Vila do Maio');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (764, 'Meevee', 'Shahrak-e Bākharz');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (765, 'Podcat', 'Khvastovichi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (766, 'Mynte', 'Kaduengang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (767, 'Jaxspan', 'Wang Nam Yen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (768, 'Eadel', 'Shimen');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (769, 'Twimbo', 'Moriki');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (770, 'Quimba', 'Saint-Quentin-en-Yvelines');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (771, 'Skippad', 'Stepanivka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (772, 'Shuffletag', 'Bautista');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (773, 'Reallinks', 'Cuogang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (774, 'Voomm', 'Bacnor East');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (775, 'Oba', 'Haparanda');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (776, 'Twimbo', 'Qiawan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (777, 'Quinu', 'Pakemitan Dua');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (778, 'Yakijo', 'Zhichu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (779, 'Skyvu', 'Lutowiska');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (780, 'Twitterbridge', 'Rokietnica');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (781, 'Eare', 'Jinta');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (782, 'Oba', 'Pilar');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (783, 'Linkbuzz', 'Härnösand');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (784, 'Browsezoom', 'Yarang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (785, 'Geba', 'Stoczek');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (786, 'Blogspan', 'Niono');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (787, 'Twimbo', 'Cereté');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (788, 'Zooxo', 'Río Guayabal de Yateras');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (789, 'Npath', 'Rzgów');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (790, 'Fliptune', 'San Narciso');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (791, 'Quinu', 'Asamankese');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (792, 'Kanoodle', 'Xingnong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (793, 'Flipstorm', 'Puerto Varas');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (794, 'Skajo', 'München');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (795, 'Yacero', 'Santiago do Cacém');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (796, 'Jayo', 'eSikhawini');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (797, 'Topiclounge', 'Cool űrhajó');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (798, 'Skinder', 'Besançon');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (799, 'Feedspan', 'Hengli');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (800, 'Izio', 'Mansa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (801, 'Mudo', 'Bantal');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (802, 'Twinder', 'Pangrumasan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (803, 'Trilia', 'Zhangguanying');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (804, 'Jabbersphere', 'Polowat');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (805, 'Mydo', 'Piotrków Trybunalski');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (806, 'Trilith', 'Donghai');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (807, 'Tagcat', 'Morteros');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (808, 'Jetpulse', 'Fuxing');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (809, 'Linkbuzz', 'Nizhniy Ufaley');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (810, 'Brainverse', 'São João dos Patos');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (811, 'Rhyzio', 'K Bang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (812, 'Buzzster', 'Quimper');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (813, 'Gabcube', 'Marquard');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (814, 'Photobean', 'Hohhot');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (815, 'Wikizz', 'Damanhūr');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (816, 'Kanoodle', 'Mariestad');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (817, 'Youspan', 'Dzüünkharaa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (818, 'Geba', 'Babica');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (819, 'Wordtune', 'Rijeka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (820, 'Gabtune', 'Wang Muang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (821, 'Oba', 'Alexandria');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (822, 'Wikizz', 'Mtsamdou');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (823, 'Vinte', 'Niebylec');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (824, 'Gabtype', 'Maragogi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (825, 'Yodo', 'Mintian');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (826, 'Kamba', 'La Peña');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (827, 'Kayveo', 'Sá');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (828, 'Feedfish', 'Novyye Cherëmushki');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (829, 'Kazu', 'Sūq ar Rabū‘');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (830, 'Voolia', 'Pouso Alegre');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (831, 'Nlounge', 'Firavitoba');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (832, 'Twitterworks', 'Cool űrhajó');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (833, 'Camimbo', 'Cililitan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (834, 'Meejo', 'Skuratovskiy');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (835, 'Jabbertype', 'Hoeryŏng');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (836, 'Rhybox', 'Anuling');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (837, 'Ailane', 'Tsotsin-Yurt');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (838, 'Meembee', '‘Amd');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (839, 'Feednation', 'Dongcun');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (840, 'Ooba', 'Pruszków');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (841, 'Eire', 'Klevan’');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (842, 'Realblab', 'Cotuí');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (843, 'Photobean', 'Sokol’niki');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (844, 'Jayo', 'Beaumont');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (845, 'Trilia', 'Toyonaka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (846, 'Devshare', 'Jiulong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (847, 'Realmix', 'Charlotte');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (848, 'Eare', 'Burqah');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (849, 'Youtags', 'Tikhvin');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (850, 'Photofeed', 'Camargo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (851, 'Kanoodle', 'Chotepe');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (852, 'Tanoodle', 'Watodei');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (853, 'Dabtype', 'Taznakht');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (854, 'Linktype', 'Kalangsari');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (855, 'Topiczoom', 'Mulanje');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (856, 'Trilith', 'Santo Domingo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (857, 'Blognation', 'Retorta');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (858, 'Buzzbean', 'Kembangkerang Satu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (859, 'Tagchat', 'Ashgabat');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (860, 'Trunyx', 'Susiec');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (861, 'Katz', 'Bačka Palanka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (862, 'Meedoo', 'Bhokadoke');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (863, 'Latz', 'Sugihmukti');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (864, 'Dynava', 'Haczów');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (865, 'Bubblebox', 'Solna');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (866, 'Skajo', 'Hospitalet De Llobregat, L''');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (867, 'Voolia', 'Tehrān');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (868, 'Dabshots', 'San Diego');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (869, 'Eidel', 'Meybod');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (870, 'Einti', 'Elbasan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (871, 'Skinder', 'Carson City');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (872, 'Oyoba', 'Žeravice');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (873, 'Chatterpoint', 'Zhongshu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (874, 'Trudoo', 'Xubu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (875, 'Brainlounge', 'Hali');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (876, 'Dabshots', 'Tugu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (877, 'Rhyloo', 'Yelan’');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (878, 'Babblestorm', 'Pyatigorsk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (879, 'Mybuzz', 'Rączna');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (880, 'Meezzy', 'Thaon-les-Vosges');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (881, 'Mydo', 'Baranusa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (882, 'Edgeify', 'Nikolayevka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (883, 'Lajo', 'Niimi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (884, 'Quinu', 'Takeo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (885, 'Podcat', 'Lao Suea Kok');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (886, 'Rhynyx', 'Sułoszowa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (887, 'Izio', 'Zmeyskaya');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (888, 'Fivebridge', 'Tambac');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (889, 'Youspan', 'Buga');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (890, 'Twitterworks', 'Vale de Santarém');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (891, 'Gabtune', 'Taraju');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (892, 'Kare', 'Kista');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (893, 'Edgeblab', 'Chropyně');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (894, 'Realblab', 'Mulandoro');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (895, 'Brainsphere', 'Akure');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (896, 'Buzzbean', 'Rovensko pod Troskami');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (897, 'Thoughtbridge', 'Lekas');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (898, 'Devify', 'Novoaleksandrovsk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (899, 'Topicblab', 'Angadanan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (900, 'Babbleblab', 'Sao Hai');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (901, 'Tambee', 'Kurumkan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (902, 'Yakidoo', 'Patos');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (903, 'Kanoodle', 'Rangpur');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (904, 'Oloo', 'Nepeña');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (905, 'Youfeed', 'Sibucao');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (906, 'Aimbo', 'Maiorca');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (907, 'Devify', 'Jianshan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (908, 'Cogibox', 'Playas');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (909, 'Tazz', 'José de Freitas');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (910, 'Linklinks', 'Henglu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (911, 'Cogidoo', 'Karangsonojabon');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (912, 'Buzzshare', 'Pengembur Dua');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (913, 'Skipstorm', 'As Sulayyil');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (914, 'Youtags', 'Gislaved');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (915, 'InnoZ', 'Karangsari');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (916, 'Skinix', 'Muyuzi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (917, 'Gigaclub', 'Gengzhuang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (918, 'Meeveo', 'Kovářská');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (919, 'Zooxo', 'Tanbu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (920, 'Teklist', 'Kupahandap');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (921, 'Kazio', 'Miguel Aleman');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (922, 'Quimba', 'Embu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (923, 'Babblestorm', 'Neftegorsk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (924, 'Mynte', 'Cigaras');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (925, 'Oozz', 'Axioúpoli');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (926, 'Kazu', 'Taza');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (927, 'Dabvine', 'Kemijärvi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (928, 'Skynoodle', 'Digby');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (929, 'Kare', 'Adirejo');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (930, 'Pixoboo', 'Debre Tabor');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (931, 'Vipe', 'Toyama-shi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (932, 'Skimia', 'Smečno');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (933, 'Dabtype', 'Ipubi');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (934, 'Skajo', 'Panggungwinong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (935, 'Feednation', 'Birātnagar');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (936, 'Voonyx', 'Stapleford');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (937, 'Realcube', 'Bogdanovich');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (938, 'Topicblab', 'Santa Cruz');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (939, 'Bluezoom', 'Fuquan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (940, 'Buzzster', 'Longcun');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (941, 'Feedbug', 'Udachny');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (942, 'Gigabox', 'Áyios Nikólaos');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (943, 'JumpXS', 'Panalingaan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (944, 'Geba', 'Dresden');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (945, 'Realpoint', 'Toki');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (946, 'Babblestorm', 'Fujisawa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (947, 'Buzzshare', 'Suhong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (948, 'Flashset', 'Ushuaia');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (949, 'Voolith', 'Picoto');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (950, 'Flipbug', 'Alfonso');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (951, 'Bluejam', 'Cibatu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (952, 'Bluezoom', 'Velký Týnec');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (953, 'Brainverse', 'Taishan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (954, 'Fanoodle', 'Baclayon');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (955, 'Realcube', 'Jianshan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (956, 'Skalith', 'Juranalas');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (957, 'Wikido', 'Hashtpar');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (958, 'Digitube', 'Suwangi Utara');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (959, 'Edgeblab', 'Ciudad Bolívar');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (960, 'Tavu', 'Fukuchiyama');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (961, 'Gigaclub', 'Apaga');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (962, 'Jatri', 'Sinargalih');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (963, 'Meezzy', 'Bijie');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (964, 'Brainlounge', 'Sanchahe');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (965, 'Livefish', 'Dongfu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (966, 'Gabtype', 'Aksarka');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (967, 'Photojam', 'Hantara');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (968, 'Gigaclub', 'Jetak Kulon');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (969, 'Dynabox', 'Gar');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (970, 'Kaymbo', 'Doong');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (971, 'Buzzshare', 'Dingchang');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (972, 'Mydo', 'Ashchysay');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (973, 'Twitterlist', 'Santa Maria');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (974, 'Talane', 'Vale');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (975, 'Dabjam', 'Xingshou');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (976, 'Dazzlesphere', 'Montgomery');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (977, 'Zoomlounge', 'Albert Town');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (978, 'Ntags', 'Yiwa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (979, 'Browsetype', 'Rakičan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (980, 'Kare', 'Höfn');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (981, 'Realcube', 'Oehaunu');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (982, 'Yodel', 'Fonte Boa');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (983, 'Bubblemix', 'Iwanuma');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (984, 'Zooveo', 'Babakanjaya');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (985, 'Jaxworks', 'Danané');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (986, 'Babbleopia', 'Pyatigorsk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (987, 'Babbleblab', 'Miracema');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (988, 'Oozz', 'Niamtougou');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (989, 'Thoughtstorm', 'Kirawsk');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (990, 'Brightbean', 'Myadzyel');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (991, 'Feedfire', 'Potrero Grande');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (992, 'Buzzshare', 'Milotice');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (993, 'Linkbuzz', 'Montpellier');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (994, 'Edgeblab', 'Asíni');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (995, 'Kazio', 'Chengbei');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (996, 'Bubbletube', 'Bayawan');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (997, 'Tagopia', 'Eslöv');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (998, 'Skyndu', 'Sandaoba');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (999, 'Zoomcast', 'Złoty Stok');
insert into restaurante_entity (codigo, nombre, nombreCiudad) values (1000, 'Realcube', 'Wieniawa');
